---
galaxy_info:
  author: Michael Hamrah
  description: Ansible Zookeeper Role
  company: http://michaelhamrah.com
  license: Apache 2
  min_ansible_version: 1.6
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your 
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
  - name: EL
    versions:
     - 6
     - 7
  #- name: GenericUNIX
  #  versions:
  #  - all
  #  - any
  #- name: Fedora
  #  versions:
  #  - all
  #  - 16
  #  - 17
  #  - 18
  #  - 19
  #  - 20
  #- name: opensuse
  #  versions:
  #  - all
  #  - 12.1
  #  - 12.2
  #  - 12.3
  #  - 13.1
  #  - 13.2
  #- name: GenericBSD
  #  versions:
  #  - all
  #  - any
  #- name: FreeBSD
  #  versions:
  #  - all
  #  - 8.0
  #  - 8.1
  #  - 8.2
  #  - 8.3
  #  - 8.4
  #  - 9.0
  #  - 9.1
  #  - 9.1
  #  - 9.2
  - name: Ubuntu
    versions:
      - raring
      - saucy
      - trusty
      - utopic
      - vivid
      - wily
      - xenial
  #- name: SLES
  #  versions:
  #  - all
  #  - 10SP3
  #  - 10SP4
  #  - 11
  #  - 11SP1
  #  - 11SP2
  #  - 11SP3
  #- name: GenericLinux
  #  versions:
  #  - all
  #  - any
  - name: Debian
    versions:
      - etch
      - lenny
      - squeeze
      - wheezy

  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
  categories:
  #- cloud
  #- cloud:ec2
  #- cloud:gce
  #- cloud:rax
  #- database
  #- database:nosql
  #- database:sql
  #- development
  #- monitoring
  #- networking
  #- packaging
  #- system
  #- web
  - platform

  galaxy_tags:
    - zookeeper
    - distributed synchronization
    - distributed hierarchical key-value store
    - synchronization service

dependencies: []
  # - ansible-java
  # - ansible-scala
  # - ansible-sbt
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
