- name: Create users
  win_user:
    name: "{{ item.name }}"
    password: "{{ item.password}}"
    state: present
    groups:
      - Users
      - Remote Desktop Users
  with_items: "{{ users }}"
  tags: localusers